[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "usda-fooddata-mcp"
version = "0.1.0"
description = "USDA FoodData Central API MCP server"
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
usda-mini-demo = "usda_mcp.demo:main"
usda-mini-server = "usda_mcp.server:main"

[tool.setuptools.packages.find]
where = ["src"]
